services:
 mysqldb:
   image: mysql
   env_file:
     - ./env/mysql_db.env
   volumes:
     - mysql-data:/var/lib/mysql
   ports:
     - "3306:3306"
# redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis:/data
volumes:
  mysql-data:
    driver: local
#  redis:
#    driver: local